auto: true

username: StrayBirds # 增加路径
baseurl: /yusmile.github.io

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 钟爱一生
url: http://beiyuu.com
feed: /atom.xml
author_info: <a href="http://beiyuu.com/">BeiYuu</a>
